Service metrics panel
evrone/bmstu_2024 pull request #16
Opened 2024-07-11 17:34 UTC by daronenko

Панель для просмотра нагрузки на сервис, времени выполнения запросов к серверу/бд, кодов ответа и расшифровок исключений при 500'ках. Для функционирования необходим Redis.

![Screenshot 2024-07-11 at 19 57 48](https://github.com/evrone/bmstu_2024/assets/57857253/dc18816f-f0aa-4dae-a9ac-46b61ecb1a7b)

![Screenshot 2024-07-11 at 20 25 06](https://github.com/evrone/bmstu_2024/assets/57857253/11b8e63e-bae0-4d41-9816-d8b775931a67)

2024-07-12 17:32 UTC, mikeGEINE requested changes
Нужен фикс на ссылки в навигации панели, чтобы они не вели на корректный адрес

2024-07-12 17:32 UTC, mikeGEINE commented on config/initializers/rails_performance.rb
> +  # config.verify_access_proc = proc { |controller| controller.current_user && controller.current_user.admin? }
кажется, здесь в комменте наш случай, мб его использовать?

2024-07-15 09:58 UTC, daronenko commented on config/initializers/rails_performance.rb
> +  # config.verify_access_proc = proc { |controller| controller.current_user && controller.current_user.admin? }
Загрузил переменную окружения `HOST` в `config/puma.rb` и добавил следующие хедеры в конфиг nginx:

```nginx
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Ssl on;  # Optional
proxy_set_header X-Forwarded-Port $server_port;
proxy_set_header X-Forwarded-Host $host
```

2024-07-15 11:25 UTC, mikeGEINE requested changes

2024-07-15 11:25 UTC, mikeGEINE commented on config/puma.rb
> +
.env подгружаем контейнером в след. релизе

2024-07-15 11:25 UTC, mikeGEINE commented on Gemfile
> +gem 'dotenv'
думаю, `dotenv`

2024-07-15 12:47 UTC, mikeGEINE approved these changes

2024-07-15 12:51 UTC, merged