Dev контейнеры
evrone/bmstu_2024 pull request #17
Opened 2024-07-12 07:09 UTC by vzalygin

Дальнейшая разработка будет вестись в контейнерах. Этот пулрик содержит все необходимые инструменты для этого. Основной список команд лежит в Makefile.

2024-07-12 07:12 UTC, vzalygin commented on docker-compose.yaml
> +    image: ghcr.io/evrone/bmstu_2024_dev
Если всем выдать токены до регистра, то можно будет не билдить окружение, а получать его

2024-07-12 09:16 UTC, vzalygin commented on .env.private.example
> +DATABASE_URL=
\n

2024-07-12 09:16 UTC, vzalygin commented on .gitignore
> +*.private
\n

2024-07-12 09:16 UTC, vzalygin commented on Procfile.dev
> +web: env RUBY_DEBUG_OPEN=true RUBY_DEBUG_PORT=12345 RUBY_DEBUG_HOST=0.0.0.0 bin/rails server -b 0.0.0.0 -p3000
\n

2024-07-12 09:16 UTC, vzalygin commented on bin/dev
> +exec foreman start -e .env.dev -f Procfile.dev "$@"
\n

2024-07-12 09:16 UTC, vzalygin commented on bmstu_2024.code-workspace
> +}
\n

2024-07-12 09:51 UTC, mikeGEINE requested changes

2024-07-12 09:51 UTC, mikeGEINE commented on docker-compose.yaml
> +    image: ghcr.io/evrone/bmstu_2024_dev
При разработке лучше всё же иметь возможность собирать окружение локально исходя из последних изменений. Всегда можно что-то где-то сломать или, наоборот, придумать, как починить, и обращение к регистру здесь будет только мешать. Лучше так не делать в dev-е

2024-07-12 09:51 UTC, mikeGEINE commented on Makefile
- [x] `setup` здесь лишь соберёт контейнеры, но нам нужно, чтобы эта команда полностью подготовила окружение. Не хватает подготовки базы данных: если мы собираем окружение заново (для этого и нужна команда), то нам нужно снова собрать чистый контейнер с базой, инициализировать базу, прогнать в ней миграции, заполнить отладочными данными (`db:seed`).
- [x] Не хватает `bundle`. Подгрузка томов точно устраняет необходимость в ней?
- [x] В целом по базе данных команд мало. Базу легко можно поломать, и только прогона миграций в том или ином порядке может быть недостаточно. Нужно оставить возможность её ручками сбросить, дропнуть, заполнить. + только на рельсу не стоит полагаться, нужен доступ к CLI в контейнере

2024-07-12 09:51 UTC, mikeGEINE commented on Dockerfile.dev
- [x] Нет гемов в контейнере. Контейнер должен быть полностью самодостаточным и независимым. Для работы контейнера однозначно понадобится полный набор гемов. Да, в случае использования docker-compose мы их примонтируем к контейнеру, а если мы не будем compose использовать?
- [x] Нет entrypoint-а. Проблема точно такая же: с compose работать будет, а без него?

2024-07-12 09:51 UTC, mikeGEINE commented on Dockerfile.dev
- [ ] Development собирается на базе alpine, а прод сейчас - на базе debian. Нужно кого-то из них поменять. Лучше прод)

2024-07-13 12:34 UTC, mikeGEINE requested changes
LGTM, кроме `bin/dev`. Перед мёрджем лучше засквошить коммиты

2024-07-13 12:34 UTC, mikeGEINE commented on Dockerfile.dev
> +RUN apk add --update docker
Зачем докер внутри контейнера?

2024-07-13 12:34 UTC, mikeGEINE commented on bin/dev
> +exec foreman start -f Procfile.dev "$@"
Дублирует 13 строку, нужно убрать

2024-07-13 12:34 UTC, mikeGEINE commented on .vscode/extensions.json
> +}
/n

2024-07-13 12:34 UTC, mikeGEINE commented on bin/importmap
Правильно ли я понимаю, что при создании приложения ты выбрал что-то другое для работы с JS вместо `importmaps`? Отсюда и вытекают зависимости на yarn, да?

В целом мы, наверное, от JS сильно не зависим и `importmaps` особо не успели бы воспользоваться, так что, думаю, не принципиально

2024-07-14 19:01 UTC, vzalygin commented on bin/importmap
При создании я использовал опции `-j esbuild --css bootstrap`

2024-07-14 19:08 UTC, vzalygin commented on Dockerfile.dev
> +RUN apk add --update docker
случайно прокралось

2024-07-15 09:28 UTC, mikeGEINE commented on .env.example
> +DATABASE_URL=
Думаю, здесь никаких секретов нет, вполне типовые значения для локалки. Тем не менее без их указания может быть не очень понятно, а что же должно быть в `.env`.

```suggestion
POSTGRES_DB=wheremylikes_development
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
DATABASE_URL=postgresql://postgres@postgres:5432
```

2024-07-15 09:31 UTC, mikeGEINE approved these changes

2024-07-15 12:04 UTC, mikeGEINE commented on docker-compose.yaml
> +      - bundle:/usr/local/bundle:cached
```suggestion
```

2024-07-15 12:04 UTC, mikeGEINE commented on docker-compose.yaml
> +  bundle:
```suggestion
```

2024-07-15 12:10 UTC, merged