Save user metrics in db
evrone/bmstu_2024 pull request #47
Opened 2024-07-18 16:21 UTC by daronenko

2024-07-18 16:25 UTC, daronenko commented
Пример использования модуля `SocialMetrics`:

```ruby
posts = [
  {
    id: 1,
    likes: [4, 2, 18, 16, 20],  # users' id
    comments: [1, 4, 18]        # users' id
  },
  {
    id: 2,
    likes: [2, 18, 5, 9, 12, 6, 10, 3],  # users' id
    comments: [6, 2, 3, 1, 4, 5]         # users' id
  },
  {
    id: 3,
    likes: [1, 4, 6],   # users' id
    comments: [19, 15]  # users' id
  }
]

friends = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]  # users' id
```

```ruby
ctx = SocialMetrics::Context.new(posts, friends)
active_friends, inactive_friends = SocialMetrics.active_friends(ctx)
average_likes = SocialMetrics.average_likes(ctx)
audience_score = SocialMetrics.audience_score(ctx, active_friends)
post_metrics = SocialMetrics.post_metrics(ctx)
average_engagement_score = SocialMetrics.get_average_engagement_score(post_metrics)
```

2024-07-22 11:08 UTC, mikeGEINE requested changes
Обсудили изменения на созвоне

2024-07-22 11:08 UTC, mikeGEINE commented on app/models/user.rb
> +  end
Функция вернёт relationships, а название функции говорит о friends. Функция, исходя из названия, должна возвращать именно друзей.

2024-07-22 11:08 UTC, mikeGEINE commented on app/models/user.rb
> +  end
Подход с написанием собственной функции рабочий, но вообще не единственный. Можно объявлять отношения между моделями с фильтрами. К примеру:
```ruby
class User < ApplicationRecord
  has_many :relationships
  has_many :friends, through: :relationships
  has_many :active_relationships, -> { where is_active: true }, class_name: 'Relationship'
  has_many :active_friends, through: :active_relationships, class_name: 'Friend', source: :friend
end
```

2024-07-22 11:08 UTC, mikeGEINE commented on app/models/relationship.rb
> +  validates :is_active, inclusion: { in: [true, false] }
`is_active` - не лучшее название в парадигме Rails. Правильнее будет назвать просто `active`, по аналогии с другими подобными функциями (например, у любой модели есть функция `changed?`, которая, по сути, так же отражает статус модели, и тоже могла бы быть `is_changed`).
Кроме того, за счёт того, что это boolean, у модели появляется предикат `is_active?`. И здесь уже точно правильнее будет просто `active?`. 
Я думаю, что лучше переименовать

2024-07-22 11:08 UTC, mikeGEINE commented on app/models/user.rb
> +  end
Мне кажется, эта функция в целом не слишком нужная.
1. Друзей можно получить через вызов friends, не проходя через relationships, за счёт обявления has_many through.
2. Как правило удобнее будет использовать список друзей, а не их идентификаторов. Ruby позволяет это делать по сути без штрафов.
3. Если очень нужны id, то их можно получить из списка друзей в любом месте через `friends.map(&:id)`. Это лучше, чем лишняя функция

2024-07-22 11:08 UTC, mikeGEINE commented on app/models/user.rb
>    end
Это точно нужная функция за исключением того, что она парсит JSON?
Точно ли у поста поля `likers` и `commentators` должны быть JSON-ами? Название предполагает, что это перечень людей, что поставили лайк или оставили комментарий; может быть тогда это должен быть массив? Такой тип поддерживается нашей базой данных, [если верить SO](https://stackoverflow.com/questions/32409820/add-an-array-column-in-rails).
Если же это чисто JSON-ы, пришедшие от VK и содержат доп поля, то:
1. Нужные поля из JSON должны стать полями модели, ненужные отбросить
2. Для идентификаторов людей, опять же, можно использовать массивы
3. Если без JSON совсем никак, то, опять же, Postgres позволяет и JSON хранить как тип
Для справки: https://guides.rubyonrails.org/active_record_postgresql.html

2024-07-22 16:31 UTC, mikeGEINE approved these changes
LGTM

2024-07-22 16:32 UTC, merged

2024-07-22 16:32 UTC, mikeGEINE commented
При мёрдже выберите Squash and merge плиз